In [3]:
import numpy as np

In [4]:
one_dimensional_array = np.array([1.2,2.4,3.5,4.7,6.1,7.2,8.3,9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [5]:
two_dimensional_array = np.array([[6,5],[11,7],[4,8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [6]:
sequence_of_integers = np.arange(5,12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [7]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[89 85 93 76 53 68]


In [8]:
random_floats_between_0_and_1 = np.random.random([6]) #random modülünün random() adlı fonksiyonunu kullanarak, 0.0 ile 1.0 arasında rastgele bir kayan noktalı sayı üretilir.
print(random_floats_between_0_and_1)

[0.76997418 0.30350173 0.89682797 0.61932701 0.00846188 0.14516465]


In [9]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.76997418 2.30350173 2.89682797 2.61932701 2.00846188 2.14516465]


In [10]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[267 255 279 228 159 204]


In [11]:
feature = np.random.randint(low=6, high=21, size=(6))
print(feature)

[17 13 20 13 10  6]


In [13]:
label = 3*(feature) + 4 #label = (3)(feature) + 4
print(label)

[55 43 64 43 34 22]


In [14]:
#label = 3*6+4 #label = (3)(6) + 4 = 22
#print(label)

In [32]:
#Task 2: Add Some Noise to the Dataset
noise = []
for i in range(6):
  n = np.random.randint(-2,2)
  noise.append(label[i]*n)

print(noise)


[0, 0, -128, -43, -68, -22]
